Features popular person api
PiotrKubiak/movie_browser pull request #15
Opened 2021-12-12 23:17 UTC by Olaf-Tarkowski

posprzątałem trochę poprzenosiłem pliki i połączyłem api dla popularnych ludzi

2021-12-12 23:22 UTC, Olaf-Tarkowski commented on src/features/Content/MoviePeople/index.js
> +import { StyledHeader, StyledSection, StyledTiles } from "../styledMovies";
przeniesiony style to folderu Content bo z niego korzysta flder i MoviePeople i MovieList tak samo jest dla Tile

2021-12-12 23:27 UTC, PawelUrbanowski074 requested changes
w sumie to nie mam większych uwag, wszystko mi się podoba, trzeba dodać tylko errora

2021-12-12 23:27 UTC, PawelUrbanowski074 commented on src/features/Content/MoviePeople/Tile/index.js
> +export default Tile;
elegancko

2021-12-12 23:27 UTC, PawelUrbanowski074 commented on src/features/Content/MoviePeople/index.js
> +export default MoviesPeople;
też super

2021-12-12 23:27 UTC, PawelUrbanowski074 commented on src/features/Content/MoviesList/Tile/index.js
> +                        {/* <Year>{release_date.substring(4,-1)}</Year> */}
trzeba będzie ogarnąć

2021-12-12 23:27 UTC, PawelUrbanowski074 commented on src/features/Content/MoviesList/content.js
>        // return (<Error />);
trzeba dodać już ten error

2021-12-13 07:57 UTC, PiotrKubiak reviewed
Kawał dobrej roboty

2021-12-13 19:35 UTC, merged