Pagination continued
PiotrKubiak/movie_browser pull request #19
Opened 2021-12-16 14:35 UTC by PiotrKubiak

Na razie pozmieniałem trochę styli żeby mi się wszystko mieściło, ale jeszcze coś nie pasuje i trzeba nad tym posiedzieć. Zobaczcie i dajcie znać jak by co to poprawie.

2021-12-17 23:11 UTC, PawelUrbanowski074 commented
Według mnie jest spoko, możemy próbować działać z tym dalej

2021-12-18 11:27 UTC, Olaf-Tarkowski requested changes

2021-12-18 11:27 UTC, Olaf-Tarkowski commented on src/features/Content/styledMovies.js
> +  font-weight: 600;
po co dajesz font jesli jest narzucony z góry 600

2021-12-18 11:27 UTC, Olaf-Tarkowski commented on src/features/Content/styledMovies.js
> +    font-weight: 600;
po co dajesz font jesli jest narzucony z góry 600

2021-12-18 16:59 UTC, closed without merging