Test pagination2
PiotrKubiak/movie_browser pull request #27
Opened 2021-12-23 10:53 UTC by PiotrKubiak

- Dodana działająca funkcja paginacji do listy filmów
- Poprawione style
- Drobne poprawki w kodzie

Proszę dać znać co o tym sądzicie i wstawie paginacje po ocenie do people

2021-12-23 18:12 UTC, Olaf-Tarkowski requested changes

2021-12-23 18:12 UTC, Olaf-Tarkowski commented on src/common/Pagination/PreviousArrow/styled.js
> +`;
stworzyłeś styled dla PreviousArrow i NextArrow ale z tego co zauważyłem te style niczym nie różnią się od siebie. Ja bym na twoim miejscy wyciągną styled.js wyżej i nie robił dwóch takich smaych.

2021-12-23 18:31 UTC, PiotrKubiak commented on src/common/Pagination/PreviousArrow/styled.js
> +`;
Ok racja 👍

2021-12-23 21:58 UTC, PawelUrbanowski074 commented on src/common/Pagination/PreviousArrow/styled.js
> +`;
zgadzam się z przedmówcą

2021-12-23 22:01 UTC, PawelUrbanowski074 reviewed
Kod bardzo w porządku, jeśli możesz to popraw tylko wspomniane wcześniej style. Super robota!

2021-12-27 10:38 UTC, PiotrKubiak commented on src/common/Pagination/PreviousArrow/styled.js
> +`;
Już poprawione

2021-12-27 10:38 UTC, PiotrKubiak commented
Teraz powinno być wszystko ok

2021-12-27 19:14 UTC, PawelUrbanowski074 reviewed
teraz już wszystko w porządku :)

2021-12-27 19:14 UTC, merged